name: fabulous
favicon: null
layout_spectrum: 0.3686388924252242
typography_spectrum: 0.743977056350559
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9306164572481066
  lightness: 0.9772512142080814
  saturation: 0.05811377405188978
  rhythmicContrast: 0.9104639447759837
purpose: []
